# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

get_neighbors_s <- function(adj_matrix, node_id, neighbor_type) {
    .Call(`_labyrinth_get_neighbors_s`, adj_matrix, node_id, neighbor_type)
}

get_neighbors_d <- function(adj_matrix, node_id, neighbor_type) {
    .Call(`_labyrinth_get_neighbors_d`, adj_matrix, node_id, neighbor_type)
}

transfer_activation_s <- function(graph, y, x, activation, loose = 1.0) {
    .Call(`_labyrinth_transfer_activation_s`, graph, y, x, activation, loose)
}

transfer_activation_d <- function(graph, y, x, activation, loose = 1.0) {
    .Call(`_labyrinth_transfer_activation_d`, graph, y, x, activation, loose)
}

activation_rate_s <- function(graph, strength, stm, loose = 1.0, threads = 0L, remove_first = FALSE, display_progress = TRUE) {
    .Call(`_labyrinth_activation_rate_s`, graph, strength, stm, loose, threads, remove_first, display_progress)
}

activation_rate_d <- function(graph, strength, stm, loose = 1.0, threads = 0L, remove_first = FALSE, display_progress = TRUE) {
    .Call(`_labyrinth_activation_rate_d`, graph, strength, stm, loose, threads, remove_first, display_progress)
}

sigmoid_t <- function(ax, ay, u = 1L) {
    .Call(`_labyrinth_sigmoid_t`, ax, ay, u)
}

spread_gram_s <- function(graph, last_activation, loose = 1.0, threads = 0L, display_progress = FALSE) {
    .Call(`_labyrinth_spread_gram_s`, graph, last_activation, loose, threads, display_progress)
}

spread_gram_d <- function(graph, last_activation, loose = 1.0, threads = 0L, display_progress = FALSE) {
    .Call(`_labyrinth_spread_gram_d`, graph, last_activation, loose, threads, display_progress)
}

gradient_s <- function(graph, activation, threads = 0L, display_progress = FALSE) {
    .Call(`_labyrinth_gradient_s`, graph, activation, threads, display_progress)
}

gradient_d <- function(graph, activation, threads = 0L, display_progress = FALSE) {
    .Call(`_labyrinth_gradient_d`, graph, activation, threads, display_progress)
}

