# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown

jobs:
  distribution-check:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - uses: actions/checkout@v1

    - name: Configure Environment
      run: |
        sudo dnf install wget git 'dnf-command(copr)' -y
        dnf copr enable iucar/cran -y
        tee > /tmp/oneAPI.repo << EOF
        [oneAPI]
        name=Intel® oneAPI repository
        baseurl=https://yum.repos.intel.com/oneapi
        enabled=1
        gpgcheck=0
        repo_gpgcheck=0
        gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
        EOF
        sudo mv /tmp/oneAPI.repo /etc/yum.repos.d
        # Install the latest oneMKL (version 2024.1)
        sudo dnf update -y
        sudo dnf install pandoc ghostscript intel-oneapi-mkl R R-flexiblas flexiblas-* R-CoprManager make automake gcc rsync -y
        sudo dnf install R-CRAN-devtools R-CRAN-checkmate R-CRAN-RcppEigen R-CRAN-fastmatch R-CRAN-tidyverse R-CRAN-pkgdown R-CRAN-data.table R-CRAN-igraph R-CRAN-knitr R-CRAN-magrittr R-CRAN-markdown R-CRAN-testthat R-CRAN-ggthemes R-CRAN-pROC R-CRAN-pbapply R-CRAN-patchwork R-CRAN-memuse R-CRAN-pryr -y
        # Install other packages
        Rscript -e "install.packages(c('matrixStats', 'RcppProgress', 'rpca', 'BiocManager'), repo = 'https://cloud.r-project.org/')"
        Rscript -e "BiocManager::install('sparseMatrixStats', ask = FALSE, update = TRUE)"
        # Clone `diffusr` package
        git clone https://github.com/randef1ned/diffusr.git
        R CMD INSTALL diffusr
        
    - name: Build site
      run: |
        devtools::document()
        devtools::load_all()
        pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        pkgdown::build_reference(topics = 'random_walk')
      shell: Rscript {0}

    - name: Deploy to GitHub pages 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4.5.0
      with:
        clean: false
        branch: gh-pages
        folder: docs
